name: flutter_starter
description: A new Flutter project.

version: 2.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cloud_firestore: ^1.0.4
  crypto: ^3.0.1
  csv: ^5.0.0
  cupertino_icons: null
  firebase_auth: ^1.0.2
  firebase_core: ^1.0.3
  flex_color_scheme: ^3.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.1.3
  get_storage: ^2.0.2
  http: ^0.13.1

dependency_overrides: null
# analyzer: 1.4.0
# intl: 0.17.0
dev_dependencies: null

flutter:
  uses-material-design: true
  assets:
    - assets/images/default.png
    - assets/images/defaultDark.png
